// Mocks generated by Mockito 5.4.6 from annotations
// in magento_storefront_flutter/test/catalog/magento_search_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:magento_storefront_flutter/core/magento_client.dart' as _i3;
import 'package:magento_storefront_flutter/core/magento_config.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMagentoConfig_0 extends _i1.SmartFake implements _i2.MagentoConfig {
  _FakeMagentoConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MagentoClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMagentoClient extends _i1.Mock implements _i3.MagentoClient {
  MockMagentoClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MagentoConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeMagentoConfig_0(this, Invocation.getter(#config)),
          )
          as _i2.MagentoConfig);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<Map<String, dynamic>> query(
    String? query, {
    Map<String, dynamic>? variables,
    Map<String, String>? additionalHeaders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [query],
              {#variables: variables, #additionalHeaders: additionalHeaders},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> mutate(
    String? mutation, {
    Map<String, dynamic>? variables,
    Map<String, String>? additionalHeaders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutate,
              [mutation],
              {#variables: variables, #additionalHeaders: additionalHeaders},
            ),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
